[package]
name = "internets-nets"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.2"
internets-interactions-macro = { path = "../interactions-macro" }

[features]
unsafe = []
no_oom = []
threads = []
