[package]
name = "internets-nets"
version = "0.1.0"
edition = "2021"

[dependencies]
cache-padded = "1.2.0"
internets-interactions-macro = { path = "../interactions-macro" }

[features]
unsafe = []
no_oom = []
threads = []
